import { OpenAPIGeneratorTarget } from '@oats-ts/openapi-common'

const generatorsMap: Record<OpenAPIGeneratorTarget, boolean> = {
  'oats/type': true,
  'oats/type-guard': true,
  'oats/type-validator': true,
  'oats/api-type': true,
  'oats/express-router': true,
  'oats/express-router-factory': true,
  'oats/express-routers-type': true,
  'oats/operation': true,
  'oats/path-deserializer': true,
  'oats/path-serializer': true,
  'oats/path-type': true,
  'oats/query-deserializer': true,
  'oats/query-serializer': true,
  'oats/query-type': true,
  'oats/cookies-type': true,
  'oats/cookie-serializer': true,
  'oats/cookie-deserializer': true,
  'oats/set-cookie-serializer': true,
  'oats/set-cookie-deserializer': true,
  'oats/request-body-validator': true,
  'oats/request-headers-deserializer': true,
  'oats/request-headers-serializer': true,
  'oats/request-headers-type': true,
  'oats/request-server-type': true,
  'oats/request-type': true,
  'oats/response-body-validator': true,
  'oats/response-headers-deserializer': true,
  'oats/response-headers-serializer': true,
  'oats/response-headers-type': true,
  'oats/response-type': true,
  'oats/response-server-type': true,
  'oats/sdk-impl': true,
  'oats/sdk-type': true,
}

export const allGenerators = Object.keys(generatorsMap) as OpenAPIGeneratorTarget[]
