import { SchemaItem } from './types'

export const oatsSchemas: SchemaItem[] = [
  {
    name: 'Additional Properties Boolean',
    description: 'Using the additionalProperties field on schemas with a boolean value',
    image: 'https://oats-ts.github.io/docs/logo.png',
    url: 'https://raw.githubusercontent.com/oats-ts/oats-schemas/master/edge-cases/additional-properties-boolean.json',
    provider: 'oats',
  },
  {
    name: 'Array schemas',
    description: 'Named array schemas, with various item types',
    image: 'https://oats-ts.github.io/docs/logo.png',
    url: 'https://raw.githubusercontent.com/oats-ts/oats-schemas/master/schemas/array-schemas.json',
    provider: 'oats',
  },
  {
    name: 'Bodies',
    description: 'Different kind of request and response body showcase',
    image: 'https://oats-ts.github.io/docs/logo.png',
    url: 'https://raw.githubusercontent.com/oats-ts/oats-schemas/master/generated-schemas/bodies.json',
    provider: 'oats',
  },
  {
    name: 'Book Store',
    description: 'Simple CRUD API mocking the inventory of a book store',
    image: 'https://oats-ts.github.io/docs/logo.png',
    url: 'https://raw.githubusercontent.com/oats-ts/oats-schemas/master/schemas/book-store.json',
    provider: 'oats',
  },
  {
    name: 'Const schemas',
    description: 'Named schemas with const (literal) values',
    image: 'https://oats-ts.github.io/docs/logo.png',
    url: 'https://raw.githubusercontent.com/oats-ts/oats-schemas/master/schemas/const-schemas.json',
    provider: 'oats',
  },
  {
    name: 'Content Parameters',
    description: 'Parameters bypassing the usual serialization, and using the content field instead',
    image: 'https://oats-ts.github.io/docs/logo.png',
    url: 'https://raw.githubusercontent.com/oats-ts/oats-schemas/master/generated-schemas/content-parameters.json',
    provider: 'oats',
  },
  {
    name: 'Cookies',
    description: 'Showcasing a simplified login flow using cookies',
    image: 'https://oats-ts.github.io/docs/logo.png',
    url: 'https://raw.githubusercontent.com/oats-ts/oats-schemas/master/schemas/cookies.json',
    provider: 'oats',
  },
  {
    name: 'Discriminated union schemas',
    description: 'Named union types, with discriminators',
    image: 'https://oats-ts.github.io/docs/logo.png',
    url: 'https://raw.githubusercontent.com/oats-ts/oats-schemas/master/schemas/discriminated-union-type-schemas.json',
    provider: 'oats',
  },
  {
    name: 'Discriminated Union With Intersection',
    description: 'Named union types with intersection types mixed in',
    image: 'https://oats-ts.github.io/docs/logo.png',
    url: 'https://raw.githubusercontent.com/oats-ts/oats-schemas/master/edge-cases/discriminated-union-with-intersection.json',
    provider: 'oats',
  },
  {
    name: 'Enum schemas',
    description: 'Named enum schemas, with various types of values',
    image: 'https://oats-ts.github.io/docs/logo.png',
    url: 'https://raw.githubusercontent.com/oats-ts/oats-schemas/master/schemas/enum-schemas.json',
    provider: 'oats',
  },
  {
    name: 'Http Methods',
    description: 'Showcasing the supported HTTP methods',
    image: 'https://oats-ts.github.io/docs/logo.png',
    url: 'https://raw.githubusercontent.com/oats-ts/oats-schemas/master/generated-schemas/methods.json',
    provider: 'oats',
  },
  {
    name: 'Ignored fields',
    description: 'Used to demonstrate ignoring certain field from certain generators using the x-ignore field',
    image: 'https://oats-ts.github.io/docs/logo.png',
    url: 'https://raw.githubusercontent.com/oats-ts/oats-schemas/master/schemas/ignored-schemas.json',
    provider: 'oats',
  },
  {
    name: 'Irregular Parameters',
    description: 'Parameters with complex types (multi-typed enum, union and intersection)',
    image: 'https://oats-ts.github.io/docs/logo.png',
    url: 'https://raw.githubusercontent.com/oats-ts/oats-schemas/master/edge-cases/irregular-parameters.json',
    provider: 'oats',
  },
  {
    name: 'Mega Enum',
    description: 'Huge enum with thousands of options',
    image: 'https://oats-ts.github.io/docs/logo.png',
    url: 'https://raw.githubusercontent.com/oats-ts/oats-schemas/master/edge-cases/mega-enum.yaml',
    provider: 'oats',
  },
  {
    name: 'Missing Content',
    description: 'Request bodies and responses with the content field missing',
    image: 'https://oats-ts.github.io/docs/logo.png',
    url: 'https://raw.githubusercontent.com/oats-ts/oats-schemas/master/edge-cases/missing-content-schema.json',
    provider: 'oats',
  },
  {
    name: 'No Operation Ids',
    description: 'Operations with a missing operationId field',
    image: 'https://oats-ts.github.io/docs/logo.png',
    url: 'https://raw.githubusercontent.com/oats-ts/oats-schemas/master/edge-cases/no-operation-ids.json',
    provider: 'oats',
  },
  {
    name: 'No Paths Object',
    description: 'Missing paths object',
    image: 'https://oats-ts.github.io/docs/logo.png',
    url: 'https://raw.githubusercontent.com/oats-ts/oats-schemas/master/edge-cases/no-paths-object.json',
    provider: 'oats',
  },
  {
    name: 'Object schemas',
    description: 'Named object schemas, with exact properties',
    image: 'https://oats-ts.github.io/docs/logo.png',
    url: 'https://raw.githubusercontent.com/oats-ts/oats-schemas/master/schemas/object-schemas.json',
    provider: 'oats',
  },
  {
    name: 'Parameters',
    description: 'Showcasing the available parameter serialization methods',
    image: 'https://oats-ts.github.io/docs/logo.png',
    url: 'https://raw.githubusercontent.com/oats-ts/oats-schemas/master/generated-schemas/parameters.json',
    provider: 'oats',
  },
  {
    name: 'Partial Content',
    description: 'Optional or missing request bodies',
    image: 'https://oats-ts.github.io/docs/logo.png',
    url: 'https://raw.githubusercontent.com/oats-ts/oats-schemas/master/schemas/partial-content.json',
    provider: 'oats',
  },
  {
    name: 'Paths With Query Parameters',
    description: 'Paths with the query string/query parameters mixed in the path',
    image: 'https://oats-ts.github.io/docs/logo.png',
    url: 'https://raw.githubusercontent.com/oats-ts/oats-schemas/master/edge-cases/paths-with-query.json',
    provider: 'oats',
  },
  {
    name: 'Primitive schemas',
    description: 'Named primitive schemas',
    image: 'https://oats-ts.github.io/docs/logo.png',
    url: 'https://raw.githubusercontent.com/oats-ts/oats-schemas/master/schemas/primitive-schemas.json',
    provider: 'oats',
  },
  {
    name: 'Record schemas',
    description: 'Named record schemas of various types',
    image: 'https://oats-ts.github.io/docs/logo.png',
    url: 'https://raw.githubusercontent.com/oats-ts/oats-schemas/master/schemas/record-schemas.json',
    provider: 'oats',
  },
  {
    name: 'Reference Target',
    description: 'Single schema, that is commonly used as an external reference target',
    image: 'https://oats-ts.github.io/docs/logo.png',
    url: 'https://raw.githubusercontent.com/oats-ts/oats-schemas/master/schemas/reference-target-schema.json',
    provider: 'oats',
  },
  {
    name: 'References',
    description: 'Remote references using the URI reference pattern',
    image: 'https://oats-ts.github.io/docs/logo.png',
    url: 'https://raw.githubusercontent.com/oats-ts/oats-schemas/master/schemas/references.json',
    provider: 'oats',
  },
  {
    name: 'Remote refs',
    description: 'Remote references spanning through multiple documents',
    image: 'https://oats-ts.github.io/docs/logo.png',
    url: 'https://raw.githubusercontent.com/oats-ts/oats-schemas/master/schemas/remote-ref-schemas.json',
    provider: 'oats',
  },
  {
    name: 'Status Code Ranges',
    description: 'Status codes given as ranges, instead of exact codes',
    image: 'https://oats-ts.github.io/docs/logo.png',
    url: 'https://raw.githubusercontent.com/oats-ts/oats-schemas/master/edge-cases/status-code-ranges.json',
    provider: 'oats',
  },
  {
    name: 'Swagger Petstore JSON',
    description: 'Slightly modified version of the official PetStore sample',
    image: 'https://oats-ts.github.io/docs/logo.png',
    url: 'https://raw.githubusercontent.com/oats-ts/oats-schemas/master/schemas/pet-store-json.json',
    provider: 'oats',
  },
  {
    name: 'Swagger Petstore YAML',
    description: 'Slightly modified version of the official PetStore sample',
    image: 'https://oats-ts.github.io/docs/logo.png',
    url: 'https://raw.githubusercontent.com/oats-ts/oats-schemas/master/schemas/pet-store-yaml.yaml',
    provider: 'oats',
  },
  {
    name: 'Tuple schemas',
    description: 'Named tuple schemas',
    image: 'https://oats-ts.github.io/docs/logo.png',
    url: 'https://raw.githubusercontent.com/oats-ts/oats-schemas/master/schemas/tuple-schemas.json',
    provider: 'oats',
  },
  {
    name: 'Union Schemas',
    description: 'Named union types without the usage of discriminators',
    image: 'https://oats-ts.github.io/docs/logo.png',
    url: 'https://raw.githubusercontent.com/oats-ts/oats-schemas/master/schemas/union-type-schemas.json',
    provider: 'oats',
  },
]
